name: social_media_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  
  # State Management
  provider: ^6.1.1
  
  # Video player for TikTok-like feed
  video_player: ^2.8.1
  chewie: ^1.7.5  # For better video player controls
  
  # Networking
  http: ^1.1.0
  dio: ^5.4.0  # Alternative HTTP client with more features
  
  # Image handling
  cached_network_image: ^3.3.0
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0  # For loading effects
  pull_to_refresh: ^2.0.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Animations
  lottie: ^3.0.0
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.3
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment and add your assets here
  # assets:
  #   - assets/images/
  #   - assets/animations/

  # Uncomment and add your fonts here
  # fonts:
  #   - family: SF Pro Display
  #     fonts:
  #       - asset: assets/fonts/SF-Pro-Display-Regular.otf
  #       - asset: assets/fonts/SF-Pro-Display-Bold.otf
  #         weight: 700